export interface Quote {
  text: string;
  author: string | null;
}

export const QUOTES: Quote[] = [
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "Get busy living or get busy dying.", author: "Stephen King" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison" },
  { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { text: "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.", author: "Henry Ford" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "Learn something new every day.", author: "Unknown" },
  { text: "Dream big. Work hard. Stay humble.", author: "Unknown" },
  { text: "Mistakes are proof you’re trying.", author: "Jennifer Lim" },
  { text: "Education is the key to unlock your future.", author: "Unknown" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Don’t just go to school, learn to grow.", author: "Unknown" },
  { text: "Believe you can, and you’re halfway there.", author: "Theodore Roosevelt" },
  { text: "Work hard in silence. Let success make the noise.", author: "Frank Ocean" },
  { text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { text: "The more you learn, the more you earn.", author: "Warren Buffett" },
  { text: "Be a student of life, not just school.", author: "Unknown" },
  { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Learning never stops.", author: "Unknown" },
  { text: "You don’t have to be perfect to be amazing.", author: "Unknown" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Read more, learn more, grow more.", author: "Unknown" },
  { text: "Small steps every day lead to big results.", author: "Unknown" },
  { text: "Don’t be afraid to ask questions.", author: "Unknown" },
  { text: "Smart is something you become, not something you are.", author: "Unknown" },
  { text: "Learning is a journey, not a race.", author: "Unknown" },
  { text: "Your education is your superpower.", author: "Unknown" },
  { text: "Try again. Fail again. Fail better.", author: "Samuel Beckett" },
  { text: "Never stop being curious.", author: "Unknown" },
  { text: "Be proud of how far you’ve come.", author: "Unknown" },
  { text: "Every day is a chance to learn something new.", author: "Unknown" },
  { text: "Your future is created by what you do today.", author: "Unknown" },
  { text: "Don’t limit your challenges. Challenge your limits.", author: "Unknown" },
  { text: "Education is your ticket to freedom.", author: "Oprah Winfrey" },
  { text: "Be the reason someone learns something new today.", author: "Unknown" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "You don’t need to be the best, just better than yesterday.", author: "Unknown" },
  { text: "Learning is a treasure that follows its owner everywhere.", author: "Chinese Proverb" },
  { text: "Success doesn’t come from what you do occasionally, but what you do consistently.", author: "Unknown" },
  { text: "Think positive, study hard, and make it happen.", author: "Unknown" },
  { text: "Be curious. Be creative. Be kind.", author: "Unknown" },
  { text: "A little progress each day adds up to big results.", author: "Unknown" },
  { text: "You learn more from failure than from success.", author: "Unknown" },
  { text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { text: "Your attitude determines your direction.", author: "Unknown" },
  { text: "Learning is your passport to the future.", author: "Unknown" },
  { text: "You are capable of amazing things.", author: "Unknown" },
  { text: "Don’t compare your chapter one to someone else’s chapter ten.", author: "Unknown" },
  { text: "Education opens doors you didn’t even know existed.", author: "Unknown" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "Keep learning. Keep growing. Keep shining.", author: "Unknown" },
  { text: "Focus on learning, not just grades.", author: "Unknown" },
  { text: "Your mindset is the key to your success.", author: "Unknown" },
  { text: "Learn to listen before you speak.", author: "Unknown" },
  { text: "The more you practice, the better you get.", author: "Unknown" },
  { text: "Never let the fear of failing stop you from learning.", author: "Unknown" },
  { text: "Ask, learn, improve, repeat.", author: "Unknown" },
  { text: "Curiosity is the first step to wisdom.", author: "Unknown" },
  { text: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { text: "Knowledge is power. Use it wisely.", author: "Unknown" },
  { text: "Be brave enough to start.", author: "Unknown" },
  { text: "Every great learner was once a beginner.", author: "Unknown" },
  { text: "Don’t be afraid to learn something difficult.", author: "Unknown" },
  { text: "Success starts with self-belief.", author: "Unknown" },
  { text: "Learning is like climbing a mountain. Enjoy the view.", author: "Unknown" },
  { text: "Stay curious, stay learning, stay growing.", author: "Unknown" },
  { text: "Don’t give up. Great things take time.", author: "Unknown" },
  { text: "Study smart, not just hard.", author: "Unknown" },
  { text: "Your effort today builds your tomorrow.", author: "Unknown" },
  { text: "Keep asking questions. That’s how you learn.", author: "Unknown" },
  { text: "You are your best investment.", author: "Unknown" },
  { text: "One book, one pen, one student can change the world.", author: "Malala Yousafzai" },
  { text: "Learn something that makes you better than you were yesterday.", author: "Unknown" },
  { text: "Dream, learn, achieve.", author: "Unknown" },
  { text: "Study now, shine later.", author: "Unknown" },
  { text: "What you learn today builds your future tomorrow.", author: "Unknown" },
  { text: "Keep learning, because life never stops teaching.", author: "Unknown" },
  { text: "Stay hungry for knowledge.", author: "Steve Jobs" },
  { text: "Make today a learning day.", author: "Unknown" },
  { text: "The best project you’ll ever work on is yourself.", author: "Unknown" },
  { text: "Every question is a doorway to discovery.", author: "Unknown" },
  { text: "Dream it. Learn it. Do it.", author: "Unknown" },
  { text: "Be kind. Be curious. Be unstoppable.", author: "Unknown" },
  { text: "There’s no limit to what you can learn.", author: "Unknown" },
  { text: "Stay focused, stay curious, stay kind.", author: "Unknown" },
  { text: "Learning is your adventure—enjoy the ride.", author: "Unknown" },
  { text: "Curiosity turns ordinary into extraordinary.", author: "Unknown" },
  { text: "Never stop improving yourself.", author: "Unknown" },
  { text: "Ask questions. Seek answers. Keep growing.", author: "Unknown" }
];